/*
* generated by Xtext
*/
package net.sb.statemachine.dsl.ui.contentassist;

import net.sb.statemachine.dsl.ui.contentassist.AbstractStmProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class StmProposalProvider extends AbstractStmProposalProvider {

}
