/*
 * generated by Xtext
 */
package net.sb.statemachine.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StmUiModule extends net.sb.statemachine.dsl.ui.AbstractStmUiModule {
	public StmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
