/*
* generated by Xtext
*/
package net.sb.statemachine.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class StmTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
