/*
* generated by Xtext
*/
package net.sb.statemachine.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.sb.statemachine.dsl.services.StmGrammarAccess;

public class StmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.sb.statemachine.dsl.parser.antlr.internal.InternalStmParser createParser(XtextTokenStream stream) {
		return new net.sb.statemachine.dsl.parser.antlr.internal.InternalStmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Statemachine";
	}
	
	public StmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
