/*
 * generated by Xtext
 */
package net.sb.statemachine.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StmRuntimeModule extends net.sb.statemachine.dsl.AbstractStmRuntimeModule {

}
